Update bump_version.yml

diff --git a/.github/workflows/bump_version.yml b/.github/workflows/bump_version.yml
--- a/.github/workflows/bump_version.yml
+++ b/.github/workflows/bump_version.yml
@@ -44,8 +44,15 @@ jobs:
           # Output the new version
           echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
 
-      - name: Check jq version
-        run: jq --version
+      - name: Verify files exist
+        run: |
+          if [ ! -f package.json ]; then echo "package.json not found!"; exit 1; fi
+          if [ ! -f package-lock.json ]; then echo "package-lock.json not found!"; exit 1; fi
+          echo "package.json exists:"
+          cat package.json
+          echo "package-lock.json exists:"
+          cat package-lock.json
+
 
 
       - name: Commit changes
